### ISSUE TITLE
Champs

### ISSUE THREAD

**Issue by Inaross** [koobzaar/lol-skins-developer#6]
how do i know which folder is which champion

**Comment by koobzaar** [comment]
If you're developing a software, check the README, there are CDTB endpoints with the ID and the key.

```
https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/champion-summary.json
```

 If you want to use the files individually, check the lol-skins - NOT lol-skins-developer.

**Comment by Inaross** [comment]
okay thank you so much (si eres español, muchas gracias tio, eres un grande)
